name: auto-deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Rebuilds and deploys the app
        uses: appleboy/ssh-actions@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            cd /var/www/html/cse.dalabsmit.in/cse
            git pull
            npm install
            npm run build
            pm2 restart cse
